Feature/Add products crud.
ekuritza/ProjetoMM pull request #2
Opened 2021-12-22 17:42 UTC by ekuritza

This code has the addition of the product CRUD.

2021-12-22 17:55 UTC, GuilhermeMLS approved these changes
Nice work man

2021-12-22 17:55 UTC, GuilhermeMLS commented on src/products/dto/create-product.dto.ts
> +  updatedAt: FormData;
I think you missed the data validation here. Read more: https://docs.nestjs.com/techniques/validation

2021-12-22 18:28 UTC, ran-j requested changes

2021-12-22 18:28 UTC, ran-j commented on docker-compose.yml
> +    container_name: kuritza
How about a nicer name to container ?

2021-12-27 18:46 UTC, PedroFellipe requested changes

2021-12-27 18:46 UTC, PedroFellipe commented on src/app.module.ts
> +    MongooseModule.forRoot('mongodb://localhost:27017/'),
you can set the string mongodb://localhost:27017/ to a enviroment variable

2021-12-27 19:32 UTC, renatops1991 requested changes

2021-12-27 19:32 UTC, renatops1991 commented on src/products/dto/product.dto.ts
> +  id: string;
Is this property needed here for product creation?

2021-12-27 19:32 UTC, renatops1991 commented on src/products/dto/product.dto.ts
> +  name: string;
You can add description and example, because when you do the documentation in swagger, it will be correct.
```suggestion
  @IsString()
  @IsNotEmpty()
   @ApiProperty({ description: 'example description', example: 'foo' })
  name: string;
```

2021-12-27 19:32 UTC, renatops1991 commented on src/products/dto/product.dto.ts
> +  status: StatusEnum;
You can validate the property with this decorator.
```suggestion
  @IsEnum(StatusEnum, {
    message: `$property must be one of these: ${Object.keys(StatusEnum)}`,
  })
  status: StatusEnum;
```

2021-12-27 19:32 UTC, renatops1991 commented on src/products/entities/products.ts
> +  status: string;
```suggestion
  status: StatusEnum;
```

2021-12-27 19:32 UTC, renatops1991 commented on src/products/schemas/product.schema.ts
> +    status: String,
I think you can use it that way
```suggestion
    status: {
      type: String,
      enum: Object.values(StatusEnum),
    },
```

2022-01-03 20:06 UTC, GuilhermeMLS approved these changes
Nice work!!

2022-01-03 20:06 UTC, GuilhermeMLS commented on src/products/entities/products.ts
> +export class Products extends Document {
```suggestion
export class Product extends Document {
```

2022-01-03 20:06 UTC, GuilhermeMLS commented on src/products/entities/products.ts
> +export class Products extends Document {
Entity names are always in singular

2022-01-03 20:07 UTC, ran-j approved these changes

2022-01-03 20:08 UTC, renatops1991 approved these changes

2022-01-12 18:40 UTC, merged