feat: Add order module and swagger
ekuritza/ProjetoMM pull request #3
Opened 2022-02-03 01:01 UTC by ekuritza

2022-02-04 12:41 UTC, PedroFellipe requested changes

2022-02-04 12:41 UTC, PedroFellipe commented on src/order/dto/order.dto.ts
> +  };
order schema and dto must to match in this case, i think that the products array must to be here too

2022-02-04 12:41 UTC, PedroFellipe commented on src/order/order-service.ts
> +    //@InjectModel('Product') private readonly productModel: Model<Product>,
remove this commented code, please

2022-02-04 12:42 UTC, PedroFellipe commented
Also, theres a lot of unit tests and integrations tests that you could to write in this PR, call us to do that bro. Especially the integrations tests will tell us that this API really works

2022-02-09 14:28 UTC, renatops1991 requested changes

2022-02-09 14:28 UTC, renatops1991 commented on src/order/dto/order.dto.ts
> +    dueDate: Date;
I think that create a new DTO to implements this field 
```suggestion
  payment: PaymentDto
```
Please, put the correct decorators for each field
```
export class PaymentDto {
    cardholder: string;
    paymentStatus: PaymentStatusEnum;
    value: number;
    dueDate: Date;
}
```

2022-02-09 14:28 UTC, renatops1991 commented on src/order/entities/order.ts
> +  };
The same thing as above

2022-02-09 14:28 UTC, renatops1991 commented on src/order/entities/order.ts
> +    },
```suggestion
  products: ProductDto[],
```
```
export class ProductDto {
      id: string;
      price: number;
      name: string;
}
```
Please, put the correct decorators for each field

2022-02-09 14:28 UTC, renatops1991 commented on src/order/order-service.ts
> +  async create(createOrderDto: CreateOrderDto) {
```suggestion
  async create(createOrderDto: CreateOrderDto): Promise<Order>{
```

2022-08-19 23:04 UTC, merged